// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFkBIMFztM_OjZSIEpP43wdVOmWdD5B4g',
    appId: '1:464713321169:web:2f7f45c04494fd394253f0',
    messagingSenderId: '464713321169',
    projectId: 'claimy-87868',
    authDomain: 'claimy-87868.firebaseapp.com',
    storageBucket: 'claimy-87868.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjTCU1_ZmSJgC9Q6zW-nDVSEdLjsX_XEk',
    appId: '1:464713321169:android:f1a69a822dcfe60a4253f0',
    messagingSenderId: '464713321169',
    projectId: 'claimy-87868',
    storageBucket: 'claimy-87868.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuDQ7a4Rqg7bIhMG7WwLDaTFmgKbaPp8U',
    appId: '1:464713321169:ios:f973a9ddcabe3b344253f0',
    messagingSenderId: '464713321169',
    projectId: 'claimy-87868',
    storageBucket: 'claimy-87868.firebasestorage.app',
    iosClientId: '464713321169-fk0k6lqo6l4j2cc5enp4eqve649p9hgr.apps.googleusercontent.com',
    iosBundleId: 'com.example.claimy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuDQ7a4Rqg7bIhMG7WwLDaTFmgKbaPp8U',
    appId: '1:464713321169:ios:f973a9ddcabe3b344253f0',
    messagingSenderId: '464713321169',
    projectId: 'claimy-87868',
    storageBucket: 'claimy-87868.firebasestorage.app',
    iosClientId: '464713321169-fk0k6lqo6l4j2cc5enp4eqve649p9hgr.apps.googleusercontent.com',
    iosBundleId: 'com.example.claimy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFkBIMFztM_OjZSIEpP43wdVOmWdD5B4g',
    appId: '1:464713321169:web:1530a9573aa6900e4253f0',
    messagingSenderId: '464713321169',
    projectId: 'claimy-87868',
    authDomain: 'claimy-87868.firebaseapp.com',
    storageBucket: 'claimy-87868.firebasestorage.app',
  );
}
